name: relase

on:
  push:
    tags:
      - "prerelease"

jobs:
  export-package:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Project build
        run: |
          mkdir build
          cmake -S library -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target package

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 
            build/mdvlib-prerelease-Linux.deb
            build/mdvlib-prerelease-Linux.tar.gz
